//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.0
//     from Assets/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/GameInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""040f2b47-40a4-4138-9778-d59196476fc8"",
            ""actions"": [
                {
                    ""name"": ""Digit1"",
                    ""type"": ""Button"",
                    ""id"": ""888beb70-0448-46e2-af81-bf4316b2e439"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit2"",
                    ""type"": ""Button"",
                    ""id"": ""0bdec177-1b8d-4428-b402-cf08db4aa945"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit3"",
                    ""type"": ""Button"",
                    ""id"": ""facec24d-1b68-48a3-a2ba-40e462bbd9dc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit4"",
                    ""type"": ""Button"",
                    ""id"": ""dba05d7d-7d48-4d6b-92e4-e6a306bc323a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit5"",
                    ""type"": ""Button"",
                    ""id"": ""90cda942-177b-4400-bf6b-d53f46b92d69"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit6"",
                    ""type"": ""Button"",
                    ""id"": ""945d1731-db38-438e-b229-88b14cba6e2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit7"",
                    ""type"": ""Button"",
                    ""id"": ""0b23bc27-b178-42ac-b3ff-bbacf935c366"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit8"",
                    ""type"": ""Button"",
                    ""id"": ""a1103fee-f9c7-4a6c-89c6-04216a9f8a3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit9"",
                    ""type"": ""Button"",
                    ""id"": ""48fbb36b-2884-4f96-b7ee-916d3448e9a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Digit0"",
                    ""type"": ""Button"",
                    ""id"": ""4e34ae3b-4402-41bb-9d48-34218402f253"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""7f8b1d9f-8836-4af1-85a9-569664b18d7f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backspace"",
                    ""type"": ""Button"",
                    ""id"": ""df64476f-4213-4e47-8e5b-1b2e36c92f6f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ab8599ad-ee57-4133-b40d-694adb3f0c53"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""222667af-1212-43da-9a19-b65c2359e47d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""473a0e23-bac0-423e-bc8c-af03c0ee2c3a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77dbf506-0991-4026-824d-8a82189d79a4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddb28bf6-f9a0-45f9-ad59-90543f27dac2"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c5d14b5-9cc3-4982-a4f5-c81dc31724bf"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93f49bd4-c210-4767-9d4c-d9596665453b"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e03467ef-cedf-41b0-a4b1-a2ef739904f7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe38dd75-bf8c-4fec-ba30-f617e87841e7"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cddb21b9-c5c5-4532-8eda-2c7acc717662"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Digit0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db2bed9c-f43f-40a1-8d19-79e0b96a84cc"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a0b42ed-88ef-47fc-9ddb-040f8e7bd44f"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backspace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Digit1 = m_Gameplay.FindAction("Digit1", throwIfNotFound: true);
        m_Gameplay_Digit2 = m_Gameplay.FindAction("Digit2", throwIfNotFound: true);
        m_Gameplay_Digit3 = m_Gameplay.FindAction("Digit3", throwIfNotFound: true);
        m_Gameplay_Digit4 = m_Gameplay.FindAction("Digit4", throwIfNotFound: true);
        m_Gameplay_Digit5 = m_Gameplay.FindAction("Digit5", throwIfNotFound: true);
        m_Gameplay_Digit6 = m_Gameplay.FindAction("Digit6", throwIfNotFound: true);
        m_Gameplay_Digit7 = m_Gameplay.FindAction("Digit7", throwIfNotFound: true);
        m_Gameplay_Digit8 = m_Gameplay.FindAction("Digit8", throwIfNotFound: true);
        m_Gameplay_Digit9 = m_Gameplay.FindAction("Digit9", throwIfNotFound: true);
        m_Gameplay_Digit0 = m_Gameplay.FindAction("Digit0", throwIfNotFound: true);
        m_Gameplay_Submit = m_Gameplay.FindAction("Submit", throwIfNotFound: true);
        m_Gameplay_Backspace = m_Gameplay.FindAction("Backspace", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, GameInputActions.Gameplay.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Digit1;
    private readonly InputAction m_Gameplay_Digit2;
    private readonly InputAction m_Gameplay_Digit3;
    private readonly InputAction m_Gameplay_Digit4;
    private readonly InputAction m_Gameplay_Digit5;
    private readonly InputAction m_Gameplay_Digit6;
    private readonly InputAction m_Gameplay_Digit7;
    private readonly InputAction m_Gameplay_Digit8;
    private readonly InputAction m_Gameplay_Digit9;
    private readonly InputAction m_Gameplay_Digit0;
    private readonly InputAction m_Gameplay_Submit;
    private readonly InputAction m_Gameplay_Backspace;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit1".
        /// </summary>
        public InputAction @Digit1 => m_Wrapper.m_Gameplay_Digit1;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit2".
        /// </summary>
        public InputAction @Digit2 => m_Wrapper.m_Gameplay_Digit2;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit3".
        /// </summary>
        public InputAction @Digit3 => m_Wrapper.m_Gameplay_Digit3;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit4".
        /// </summary>
        public InputAction @Digit4 => m_Wrapper.m_Gameplay_Digit4;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit5".
        /// </summary>
        public InputAction @Digit5 => m_Wrapper.m_Gameplay_Digit5;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit6".
        /// </summary>
        public InputAction @Digit6 => m_Wrapper.m_Gameplay_Digit6;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit7".
        /// </summary>
        public InputAction @Digit7 => m_Wrapper.m_Gameplay_Digit7;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit8".
        /// </summary>
        public InputAction @Digit8 => m_Wrapper.m_Gameplay_Digit8;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit9".
        /// </summary>
        public InputAction @Digit9 => m_Wrapper.m_Gameplay_Digit9;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Digit0".
        /// </summary>
        public InputAction @Digit0 => m_Wrapper.m_Gameplay_Digit0;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Submit".
        /// </summary>
        public InputAction @Submit => m_Wrapper.m_Gameplay_Submit;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/Backspace".
        /// </summary>
        public InputAction @Backspace => m_Wrapper.m_Gameplay_Backspace;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Digit1.started += instance.OnDigit1;
            @Digit1.performed += instance.OnDigit1;
            @Digit1.canceled += instance.OnDigit1;
            @Digit2.started += instance.OnDigit2;
            @Digit2.performed += instance.OnDigit2;
            @Digit2.canceled += instance.OnDigit2;
            @Digit3.started += instance.OnDigit3;
            @Digit3.performed += instance.OnDigit3;
            @Digit3.canceled += instance.OnDigit3;
            @Digit4.started += instance.OnDigit4;
            @Digit4.performed += instance.OnDigit4;
            @Digit4.canceled += instance.OnDigit4;
            @Digit5.started += instance.OnDigit5;
            @Digit5.performed += instance.OnDigit5;
            @Digit5.canceled += instance.OnDigit5;
            @Digit6.started += instance.OnDigit6;
            @Digit6.performed += instance.OnDigit6;
            @Digit6.canceled += instance.OnDigit6;
            @Digit7.started += instance.OnDigit7;
            @Digit7.performed += instance.OnDigit7;
            @Digit7.canceled += instance.OnDigit7;
            @Digit8.started += instance.OnDigit8;
            @Digit8.performed += instance.OnDigit8;
            @Digit8.canceled += instance.OnDigit8;
            @Digit9.started += instance.OnDigit9;
            @Digit9.performed += instance.OnDigit9;
            @Digit9.canceled += instance.OnDigit9;
            @Digit0.started += instance.OnDigit0;
            @Digit0.performed += instance.OnDigit0;
            @Digit0.canceled += instance.OnDigit0;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Backspace.started += instance.OnBackspace;
            @Backspace.performed += instance.OnBackspace;
            @Backspace.canceled += instance.OnBackspace;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Digit1.started -= instance.OnDigit1;
            @Digit1.performed -= instance.OnDigit1;
            @Digit1.canceled -= instance.OnDigit1;
            @Digit2.started -= instance.OnDigit2;
            @Digit2.performed -= instance.OnDigit2;
            @Digit2.canceled -= instance.OnDigit2;
            @Digit3.started -= instance.OnDigit3;
            @Digit3.performed -= instance.OnDigit3;
            @Digit3.canceled -= instance.OnDigit3;
            @Digit4.started -= instance.OnDigit4;
            @Digit4.performed -= instance.OnDigit4;
            @Digit4.canceled -= instance.OnDigit4;
            @Digit5.started -= instance.OnDigit5;
            @Digit5.performed -= instance.OnDigit5;
            @Digit5.canceled -= instance.OnDigit5;
            @Digit6.started -= instance.OnDigit6;
            @Digit6.performed -= instance.OnDigit6;
            @Digit6.canceled -= instance.OnDigit6;
            @Digit7.started -= instance.OnDigit7;
            @Digit7.performed -= instance.OnDigit7;
            @Digit7.canceled -= instance.OnDigit7;
            @Digit8.started -= instance.OnDigit8;
            @Digit8.performed -= instance.OnDigit8;
            @Digit8.canceled -= instance.OnDigit8;
            @Digit9.started -= instance.OnDigit9;
            @Digit9.performed -= instance.OnDigit9;
            @Digit9.canceled -= instance.OnDigit9;
            @Digit0.started -= instance.OnDigit0;
            @Digit0.performed -= instance.OnDigit0;
            @Digit0.canceled -= instance.OnDigit0;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Backspace.started -= instance.OnBackspace;
            @Backspace.performed -= instance.OnBackspace;
            @Backspace.canceled -= instance.OnBackspace;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "Digit1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Digit0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDigit0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Submit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSubmit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Backspace" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackspace(InputAction.CallbackContext context);
    }
}
